### ISSUE TITLE
Not clear on section 2 instructions

### ISSUE THREAD

**Issue by geraldmaboshe** [BongoHive/javascript-phase-1-geraldMaboshe#1]
**Is this question about this assignment?**
Yes 

**Describe your question**
What does this mean?
Store an estimated amount per day (as a number).
Calculate how many you would eat total for the rest of your life.
Output the result to the screen like so: "You will need NN to last you until the ripe old age of X".

**Comment by OlivierJM** [comment]
Kindly clarify your question

**Comment by geraldmaboshe** [comment]
The instructions below are not clear. Something seems to be missing. Just read through the parts below.
*Store an estimated amount per day (as a number).?
*Calculate how many you would eat total for the rest of your life.?

**Comment by OlivierJM** [comment]
Hi @geraldMaboshe 
Thanks for raising that, here is a scenario of that question 
imagine you have a specific type of food that you like and you would love to know how long it will last you for your entire lifetime, the amount per day is a number, the last question you use the values you previously created to calculate the total number of measures of that specific type of food you need in your lifetime.
I hope this explanation helps, it is not specific, I think what matters here is the variables and the formula for the last point.

**Comment by geraldmaboshe** [comment]
Thank you @OlivierJM. It's now clear

**Comment by OlivierJM** [comment]
Awesome.
